new TypeIt('#element', {
  speed: 100
})
  .type('Hello stranger')
  .pause(2000)
  .delete(8)
  .type('visitor')
  .pause(1000)
  .type(', my name is Buzz')
  .pause(2000)
  .delete(4)
  .type('<em>Felipe Schossler</em>')
  .pause(1000)
  .type(', I have 25 years old')
  .pause(1000)
  .type(', working as <em>SRE</em> at RD Station, located at the Florianópolis city')
  .pause(1000)
  .type('. I\'m passionate about technology')
  .pause(1000)
  .type(', League of Legends')
  .pause(2000)
  .delete(17)
  .type('games')
  .pause(2000)
  .type(', investments and books.')
  .pause(2000)
  .type(' That\'s it folks! <img src="https://i.pinimg.com/originals/63/d3/8d/63d38d8cbba4335a6d28b5e19f67be8d.png" alt="Heart Emoji" width="40" height="40">')
